"""replace query and answer with summary column

Revision ID: 29e5f669703d
Revises: aed19d88a6aa
Create Date: 2026-07-11 18:15:50.151248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e5f669703d'
down_revision: Union[str, Sequence[str], None] = 'aed19d88a6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary', sa.String(), nullable=False))
    op.drop_column('sessions', 'query')
    op.drop_column('sessions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'summary')
    # ### end Alembic commands ###
