"""add understanding_rounds table

Revision ID: 5124118d515c
Revises: b5702b4ccf58
Create Date: 2026-07-25 21:42:34.555913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5124118d515c'
down_revision: Union[str, Sequence[str], None] = 'b5702b4ccf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('understanding_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('new_columns_covered', sa.JSON(), nullable=False),
    sa.Column('new_observations_count', sa.Integer(), nullable=False),
    sa.Column('row_gaps_remaining', sa.Integer(), nullable=False),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('understanding_rounds')
    # ### end Alembic commands ###
