"""add modeling sufficiency fields to briefs and observations

Revision ID: 859dce45f1c7
Revises: 5124118d515c
Create Date: 2026-07-26 09:58:15.583242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859dce45f1c7'
down_revision: Union[str, Sequence[str], None] = '5124118d515c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modeling_briefs', sa.Column('entity_heterogeneity_notes', sa.String(), nullable=True))
    op.add_column('modeling_briefs', sa.Column('validation_anchor', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('observations', sa.Column('analysis_type', sa.String(), nullable=True))
    op.add_column('observations', sa.Column('evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'evidence')
    op.drop_column('observations', 'analysis_type')
    op.drop_column('observations', 'entities')
    op.drop_column('modeling_briefs', 'validation_anchor')
    op.drop_column('modeling_briefs', 'entity_heterogeneity_notes')
    # ### end Alembic commands ###
