"""add embedding_model column to sessions

Revision ID: aed19d88a6aa
Revises: 746ac5ccfd42
Create Date: 2026-07-11 07:27:37.826888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed19d88a6aa'
down_revision: Union[str, Sequence[str], None] = '746ac5ccfd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('embedding_model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'embedding_model')
    # ### end Alembic commands ###
